## Pandas
1. Series
2. DataFrame
3. Pandas basic operations

In [2]:
import pandas as pd
import numpy as np

In [119]:
# creating matrix of 5,4 data
np.arange(0, 40).reshape(10,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [120]:
## create a DataFrame
index=["R1","R2","R3","R4","R5","R6","R7","R8","R9","R10"]
column=["col1","col2","col3","col4"]
df=pd.DataFrame(data=np.arange(0, 40).reshape(10,4), columns=column, index=index)

In [13]:
type(df)

pandas.core.frame.DataFrame

In [26]:
df

col1  col2  col3  col4
R1      0     1     2     3
R2      4     5     6     7
R3      8     9    10    11
R4     12    13    14    15
R5     16    17    18    19
R6     20    21    22    23
R7     24    25    26    27
R8     28    29    30    31
R9     32    33    34    35
R10    36    37    38    39

In [27]:
df.head(2)

col1  col2  col3  col4
R1     0     1     2     3
R2     4     5     6     7

In [28]:
df.tail(2)

col1  col2  col3  col4
R9     32    33    34    35
R10    36    37    38    39

In [121]:
df.describe()

col1       col2       col3       col4
count  10.000000  10.000000  10.000000  10.000000
mean   18.000000  19.000000  20.000000  21.000000
std    12.110601  12.110601  12.110601  12.110601
min     0.000000   1.000000   2.000000   3.000000
25%     9.000000  10.000000  11.000000  12.000000
50%    18.000000  19.000000  20.000000  21.000000
75%    27.000000  28.000000  29.000000  30.000000
max    36.000000  37.000000  38.000000  39.000000

In [31]:
# retrieve only columns
df[["col1","col2","col3"]]

col1  col2  col3
R1      0     1     2
R2      4     5     6
R3      8     9    10
R4     12    13    14
R5     16    17    18
R6     20    21    22
R7     24    25    26
R8     28    29    30
R9     32    33    34
R10    36    37    38

In [32]:
type(df[["col1","col2","col3"]])

pandas.core.frame.DataFrame

In [33]:
df["col1"]

R1      0
R2      4
R3      8
R4     12
R5     16
R6     20
R7     24
R8     28
R9     32
R10    36
Name: col1, dtype: int32

In [34]:
type(df["col1"])

pandas.core.series.Series

In [37]:
# using loc we can get row data
df.loc[["R1","R3"]]

col1  col2  col3  col4
R1     0     1     2     3
R3     8     9    10    11

In [46]:
# using iloc to get row data from DataFrame
a=df.iloc[0:10:3, 0:4:2]
print(a)

     col1  col3
R1      0     2
R4     12    14
R7     24    26
R10    36    38


In [47]:
a.describe()

col1       col3
count   4.000000   4.000000
mean   18.000000  20.000000
std    15.491933  15.491933
min     0.000000   2.000000
25%     9.000000  11.000000
50%    18.000000  20.000000
75%    27.000000  29.000000
max    36.000000  38.000000

In [60]:
# to retrive only 1st and 3rd row
abc=df.iloc[0:4]
print(abc)

    col1  col2  col3  col4
R1     0     1     2     3
R2     4     5     6     7
R3     8     9    10    11
R4    12    13    14    15


In [53]:
df.iloc[2:4:1, 1:3:1]

    col2  col3
R3     9    10
R4    13    14


In [55]:
df.iloc[2:4:1, 1:3:1].values

array([[ 9, 10],
       [13, 14]])

In [64]:
df1=pd.DataFrame([[1,2,np.nan],[4,np.nan,5]], index=["R1","R2"],columns=["Col1","Col2","Col3"])

In [65]:
print(df1)

    Col1  Col2  Col3
R1     1   2.0   NaN
R2     4   NaN   5.0


In [68]:
# to find out nan values
df1.isnull()

Col1   Col2   Col3
R1  False  False   True
R2  False   True  False

In [70]:
# count of the null values in a row
df1.isnull().sum()

Col1    0
Col2    1
Col3    1
dtype: int64

In [74]:
df1.isna().sum()

Col1    0
Col2    1
Col3    1
dtype: int64

In [75]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, R1 to R2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col1    2 non-null      int64  
 1   Col2    1 non-null      float64
 2   Col3    1 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 64.0+ bytes


In [77]:
# value_counts() will be used on series only
df['col1'].value_counts()

col1
0     1
4     1
8     1
12    1
16    1
20    1
24    1
28    1
32    1
36    1
Name: count, dtype: int64

In [79]:
df['col1'].unique()

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

### IMP find the dataset is balanced or imbalaced

In [81]:
df["col1"].nunique()

10

In [88]:
df2=pd.DataFrame({'A':[1,2,3], 'B':[1,1,1]})

In [89]:
print(df2)

   A  B
0  1  1
1  2  1
2  3  1


In [85]:
print(df2['B'].nunique(), df2['A'].nunique())

1 3


In [95]:
# finding out unique counts in a column
df.nunique(axis=0)

col1    10
col2    10
col3    10
col4    10
dtype: int64

In [96]:
# finding out unique counts in a Row
df.nunique(axis=1)

R1     4
R2     4
R3     4
R4     4
R5     4
R6     4
R7     4
R8     4
R9     4
R10    4
dtype: int64

In [102]:
# getting the subset dataframe where particular values are > 20
df[df["col1"]>=20]

col1  col2  col3  col4
R6     20    21    22    23
R7     24    25    26    27
R8     28    29    30    31
R9     32    33    34    35
R10    36    37    38    39

In [103]:
df.to_csv('test.csv', index=False)
df1.to_csv('test2.csv', index=False)
df2.to_csv('test3.csv', index=False)

In [106]:
df.to_excel('test.xlsx')
df1.to_excel('test2.xlsx')
df2.to_excel('test3.xlsx')

In [107]:
# jason data

data = '{"employee_name":"deep","email":"dnarayanchaurasiya@gmail.com","job_profile":[{"title":"Team_lead","role":"developer"}]}'

In [108]:
data

'{"employee_name":"deep","email":"dnarayanchaurasiya@gmail.com","job_profile":[{"title":"Team_lead","role":"developer"}]}'

In [109]:
pd.read_json(data)

employee_name                         email  \
0          deep  dnarayanchaurasiya@gmail.com   

                                   job_profile  
0  {'title': 'Team_lead', 'role': 'developer'}

In [111]:
df4=pd.read_json(data)

In [112]:
dict(df4['job_profile'])[0]['role']

'developer'

In [113]:
data

'{"employee_name":"deep","email":"dnarayanchaurasiya@gmail.com","job_profile":[{"title":"Team_lead","role":"developer"}]}'

In [117]:
# orientation

pd.read_json(data, orient='records')

employee_name                         email  \
0          deep  dnarayanchaurasiya@gmail.com   

                                   job_profile  
0  {'title': 'Team_lead', 'role': 'developer'}

In [115]:
pd.read_json(data, orient='index')

0
employee_name                                           deep
email                           dnarayanchaurasiya@gmail.com
job_profile    [{'title': 'Team_lead', 'role': 'developer'}]

In [116]:
pd.read_json(data, orient='columns')

employee_name                         email  \
0          deep  dnarayanchaurasiya@gmail.com   

                                   job_profile  
0  {'title': 'Team_lead', 'role': 'developer'}