## Pandas
1. Series
2. DataFrame
3. Pandas basic operations

In [2]:
import pandas as pd
import numpy as np

In [119]:
# creating matrix of 5,4 data
np.arange(0, 40).reshape(10,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [120]:
## create a DataFrame
index=["R1","R2","R3","R4","R5","R6","R7","R8","R9","R10"]
column=["col1","col2","col3","col4"]
df=pd.DataFrame(data=np.arange(0, 40).reshape(10,4), columns=column, index=index)

In [13]:
type(df)

pandas.core.frame.DataFrame

In [26]:
df

col1  col2  col3  col4
R1      0     1     2     3
R2      4     5     6     7
R3      8     9    10    11
R4     12    13    14    15
R5     16    17    18    19
R6     20    21    22    23
R7     24    25    26    27
R8     28    29    30    31
R9     32    33    34    35
R10    36    37    38    39

In [27]:
df.head(2)

col1  col2  col3  col4
R1     0     1     2     3
R2     4     5     6     7

In [28]:
df.tail(2)

col1  col2  col3  col4
R9     32    33    34    35
R10    36    37    38    39

In [121]:
df.describe()

col1       col2       col3       col4
count  10.000000  10.000000  10.000000  10.000000
mean   18.000000  19.000000  20.000000  21.000000
std    12.110601  12.110601  12.110601  12.110601
min     0.000000   1.000000   2.000000   3.000000
25%     9.000000  10.000000  11.000000  12.000000
50%    18.000000  19.000000  20.000000  21.000000
75%    27.000000  28.000000  29.000000  30.000000
max    36.000000  37.000000  38.000000  39.000000

In [31]:
# retrieve only columns
df[["col1","col2","col3"]]

col1  col2  col3
R1      0     1     2
R2      4     5     6
R3      8     9    10
R4     12    13    14
R5     16    17    18
R6     20    21    22
R7     24    25    26
R8     28    29    30
R9     32    33    34
R10    36    37    38

In [32]:
type(df[["col1","col2","col3"]])

pandas.core.frame.DataFrame

In [33]:
df["col1"]

R1      0
R2      4
R3      8
R4     12
R5     16
R6     20
R7     24
R8     28
R9     32
R10    36
Name: col1, dtype: int32

In [34]:
type(df["col1"])

pandas.core.series.Series

In [37]:
# using loc we can get row data
df.loc[["R1","R3"]]

col1  col2  col3  col4
R1     0     1     2     3
R3     8     9    10    11

In [46]:
# using iloc to get row data from DataFrame
a=df.iloc[0:10:3, 0:4:2]
print(a)

     col1  col3
R1      0     2
R4     12    14
R7     24    26
R10    36    38


In [47]:
a.describe()

col1       col3
count   4.000000   4.000000
mean   18.000000  20.000000
std    15.491933  15.491933
min     0.000000   2.000000
25%     9.000000  11.000000
50%    18.000000  20.000000
75%    27.000000  29.000000
max    36.000000  38.000000

In [60]:
# to retrive only 1st and 3rd row
abc=df.iloc[0:4]
print(abc)

    col1  col2  col3  col4
R1     0     1     2     3
R2     4     5     6     7
R3     8     9    10    11
R4    12    13    14    15


In [53]:
df.iloc[2:4:1, 1:3:1]

    col2  col3
R3     9    10
R4    13    14


In [55]:
df.iloc[2:4:1, 1:3:1].values

array([[ 9, 10],
       [13, 14]])

In [64]:
df1=pd.DataFrame([[1,2,np.nan],[4,np.nan,5]], index=["R1","R2"],columns=["Col1","Col2","Col3"])

In [65]:
print(df1)

    Col1  Col2  Col3
R1     1   2.0   NaN
R2     4   NaN   5.0


In [68]:
# to find out nan values
df1.isnull()

Col1   Col2   Col3
R1  False  False   True
R2  False   True  False

In [70]:
# count of the null values in a row
df1.isnull().sum()

Col1    0
Col2    1
Col3    1
dtype: int64

In [74]:
df1.isna().sum()

Col1    0
Col2    1
Col3    1
dtype: int64

In [75]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, R1 to R2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col1    2 non-null      int64  
 1   Col2    1 non-null      float64
 2   Col3    1 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 64.0+ bytes


In [77]:
# value_counts() will be used on series only
df['col1'].value_counts()

col1
0     1
4     1
8     1
12    1
16    1
20    1
24    1
28    1
32    1
36    1
Name: count, dtype: int64

In [79]:
df['col1'].unique()

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

### IMP find the dataset is balanced or imbalaced

In [81]:
df["col1"].nunique()

10

In [88]:
df2=pd.DataFrame({'A':[1,2,3], 'B':[1,1,1]})

In [89]:
print(df2)

   A  B
0  1  1
1  2  1
2  3  1


In [85]:
print(df2['B'].nunique(), df2['A'].nunique())

1 3


In [95]:
# finding out unique counts in a column
df.nunique(axis=0)

col1    10
col2    10
col3    10
col4    10
dtype: int64

In [96]:
# finding out unique counts in a Row
df.nunique(axis=1)

R1     4
R2     4
R3     4
R4     4
R5     4
R6     4
R7     4
R8     4
R9     4
R10    4
dtype: int64

In [102]:
# getting the subset dataframe where particular values are > 20
df[df["col1"]>=20]

col1  col2  col3  col4
R6     20    21    22    23
R7     24    25    26    27
R8     28    29    30    31
R9     32    33    34    35
R10    36    37    38    39

In [103]:
df.to_csv('test.csv', index=False)
df1.to_csv('test2.csv', index=False)
df2.to_csv('test3.csv', index=False)

In [106]:
df.to_excel('test.xlsx')
df1.to_excel('test2.xlsx')
df2.to_excel('test3.xlsx')

In [107]:
# jason data

data = '{"employee_name":"deep","email":"dnarayanchaurasiya@gmail.com","job_profile":[{"title":"Team_lead","role":"developer"}]}'

In [108]:
data

'{"employee_name":"deep","email":"dnarayanchaurasiya@gmail.com","job_profile":[{"title":"Team_lead","role":"developer"}]}'

In [109]:
pd.read_json(data)

employee_name                         email  \
0          deep  dnarayanchaurasiya@gmail.com   

                                   job_profile  
0  {'title': 'Team_lead', 'role': 'developer'}

In [111]:
df4=pd.read_json(data)

In [112]:
dict(df4['job_profile'])[0]['role']

'developer'

In [113]:
data

'{"employee_name":"deep","email":"dnarayanchaurasiya@gmail.com","job_profile":[{"title":"Team_lead","role":"developer"}]}'

In [117]:
# orientation

pd.read_json(data, orient='records')

employee_name                         email  \
0          deep  dnarayanchaurasiya@gmail.com   

                                   job_profile  
0  {'title': 'Team_lead', 'role': 'developer'}

In [115]:
pd.read_json(data, orient='index')

0
employee_name                                           deep
email                           dnarayanchaurasiya@gmail.com
job_profile    [{'title': 'Team_lead', 'role': 'developer'}]

In [116]:
pd.read_json(data, orient='columns')

employee_name                         email  \
0          deep  dnarayanchaurasiya@gmail.com   

                                   job_profile  
0  {'title': 'Team_lead', 'role': 'developer'}

In [123]:
df.to_json()

'{"col1":{"R1":0,"R2":4,"R3":8,"R4":12,"R5":16,"R6":20,"R7":24,"R8":28,"R9":32,"R10":36},"col2":{"R1":1,"R2":5,"R3":9,"R4":13,"R5":17,"R6":21,"R7":25,"R8":29,"R9":33,"R10":37},"col3":{"R1":2,"R2":6,"R3":10,"R4":14,"R5":18,"R6":22,"R7":26,"R8":30,"R9":34,"R10":38},"col4":{"R1":3,"R2":7,"R3":11,"R4":15,"R5":19,"R6":23,"R7":27,"R8":31,"R9":35,"R10":39}}'

In [124]:
df.to_json(orient='columns')

'{"col1":{"R1":0,"R2":4,"R3":8,"R4":12,"R5":16,"R6":20,"R7":24,"R8":28,"R9":32,"R10":36},"col2":{"R1":1,"R2":5,"R3":9,"R4":13,"R5":17,"R6":21,"R7":25,"R8":29,"R9":33,"R10":37},"col3":{"R1":2,"R2":6,"R3":10,"R4":14,"R5":18,"R6":22,"R7":26,"R8":30,"R9":34,"R10":38},"col4":{"R1":3,"R2":7,"R3":11,"R4":15,"R5":19,"R6":23,"R7":27,"R8":31,"R9":35,"R10":39}}'

In [125]:
df.to_json(orient='records')

'[{"col1":0,"col2":1,"col3":2,"col4":3},{"col1":4,"col2":5,"col3":6,"col4":7},{"col1":8,"col2":9,"col3":10,"col4":11},{"col1":12,"col2":13,"col3":14,"col4":15},{"col1":16,"col2":17,"col3":18,"col4":19},{"col1":20,"col2":21,"col3":22,"col4":23},{"col1":24,"col2":25,"col3":26,"col4":27},{"col1":28,"col2":29,"col3":30,"col4":31},{"col1":32,"col2":33,"col3":34,"col4":35},{"col1":36,"col2":37,"col3":38,"col4":39}]'

In [127]:
# header = none means it skips 1st row of data being converted into header
df5 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)

In [128]:
df5.head(5)

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [129]:
df5.describe()

0           1           2           3           4           5   \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573   
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000   
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

               6           7           8           9           10          11  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     2.295112    2.029270    0.361854    1.590899    5.058090    0.957449   
std      0.625851    0.998859    0.124453    0.572359    2.318286    0.228572   
min      0.980000    0.340000    0.130000    0.410000    1.280000    0.480000   
25%      1.742500    1.205000    0.270000    1.250000    3.220000    0.782500   
50%      2.355000    2.135000    0.340000    1.555000    4.690000    0.965000   
75%      2.800000    2.875000    0.437500    1.950000    6.200000    1.120000   
max      3.880000    5.080000    0.660000    3.580000   13.000000    1.710000   

               12           13  
count  178.000000   178.000000  
mean     2.611685   746.893258  
std      0.709990   314.907474  
min      1.270000   278.000000  
25%      1.937500   500.500000  
50%      2.780000   673.500000  
75%      3.170000   985.000000  
max      4.000000  1680.000000